apiVersion: v1
kind: Secret
metadata:
  name: insuranceiq-secrets
  namespace: insuranceiq
type: Opaque
stringData:
  db-password: "root"
  jwt-secret: "InsuranceIQSecretKey2024VeryLongSecretKeyForHS256AlgorithmMinimum256Bits"
  service-secret: "InsuranceIQInternalServiceSecret2024"
